// Copyright 2026 Carlos Marques
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package controllers

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	declarestv1alpha1 "github.com/crmarques/declarest/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/dynamic/dynamicinformer"
	"k8s.io/client-go/tools/cache"
	k8sevents "k8s.io/client-go/tools/events"
	"k8s.io/client-go/util/workqueue"
	"sigs.k8s.io/controller-runtime/pkg/client"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

const (
	generatedResourceResyncInterval    = 10 * time.Minute
	generatedResourceWorkerCount       = 2
	generatedResourceStatusLogKey      = "generatedResource"
	generatedResourceOriginAnnotation  = declarestv1alpha1.CRDGeneratorOwnerAnnotation
	generatedResourceReasonSyncFailed  = "SyncFailed"
	generatedResourceReasonSyncSuccess = "Applied"
)

// GeneratedResourceReconciler is a metacontroller that reconciles instances of
// any CRD generated by a CRDGenerator. It uses a single
// `dynamicinformer.DynamicSharedInformerFactory` shared across all generated
// GVRs; CRDGeneratorReconciler calls EnsureWatch / StopWatch to drive the
// factory as CRDs are created or removed.
type GeneratedResourceReconciler struct {
	manager.Runnable

	Client        client.Client
	DynamicClient dynamic.Interface
	Recorder      k8sevents.EventRecorder
	Conflicts     *ConflictIndex

	factory dynamicinformer.DynamicSharedInformerFactory

	mu      sync.Mutex
	watches map[schema.GroupVersionResource]generatedWatchEntry
	queue   workqueue.TypedRateLimitingInterface[generatedWorkItem]
	started bool
	stopCh  chan struct{}
}

type generatedWatchEntry struct {
	generator types.NamespacedName
	kind      string
	stop      chan struct{}
}

type generatedWorkItem struct {
	GVR       schema.GroupVersionResource
	Kind      string
	Key       string // namespace/name
	Generator types.NamespacedName
	IsDelete  bool
	Tombstone *unstructured.Unstructured
}

// NewGeneratedResourceReconciler returns an initialised reconciler suitable for
// Manager.Add.
func NewGeneratedResourceReconciler(
	kubeClient client.Client,
	dynamicClient dynamic.Interface,
	recorder k8sevents.EventRecorder,
	conflicts *ConflictIndex,
) *GeneratedResourceReconciler {
	return &GeneratedResourceReconciler{
		Client:        kubeClient,
		DynamicClient: dynamicClient,
		Recorder:      recorder,
		Conflicts:     conflicts,
		watches:       make(map[schema.GroupVersionResource]generatedWatchEntry),
		stopCh:        make(chan struct{}),
	}
}

// Start satisfies manager.Runnable. It boots the shared workqueue and blocks
// until ctx is cancelled.
func (r *GeneratedResourceReconciler) Start(ctx context.Context) error {
	r.mu.Lock()
	r.queue = workqueue.NewTypedRateLimitingQueue[generatedWorkItem](workqueue.DefaultTypedControllerRateLimiter[generatedWorkItem]())
	r.factory = dynamicinformer.NewDynamicSharedInformerFactory(r.DynamicClient, generatedResourceResyncInterval)
	r.started = true
	r.mu.Unlock()

	for i := 0; i < generatedResourceWorkerCount; i++ {
		go r.worker(ctx)
	}

	<-ctx.Done()

	r.mu.Lock()
	r.queue.ShutDown()
	r.factory.Shutdown()
	close(r.stopCh)
	r.mu.Unlock()
	return nil
}

// EnsureWatch registers a dynamic informer for the given GVR if one does not
// already exist. Idempotent.
func (r *GeneratedResourceReconciler) EnsureWatch(gvr GeneratedGVR, generator types.NamespacedName) error {
	schemaGVR := schema.GroupVersionResource{
		Group:    gvr.Group,
		Version:  gvr.Version,
		Resource: gvr.Resource,
	}

	r.mu.Lock()
	if !r.started {
		r.mu.Unlock()
		return fmt.Errorf("generated resource reconciler is not started")
	}
	if _, exists := r.watches[schemaGVR]; exists {
		r.mu.Unlock()
		return nil
	}
	stop := make(chan struct{})
	r.watches[schemaGVR] = generatedWatchEntry{generator: generator, kind: gvr.Kind, stop: stop}
	factory := r.factory
	queue := r.queue
	r.mu.Unlock()

	informer := factory.ForResource(schemaGVR).Informer()
	_, err := informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj any) {
			item, ok := informerItemFromObject(schemaGVR, gvr.Kind, generator, obj, false)
			if ok {
				queue.Add(item)
			}
		},
		UpdateFunc: func(_, obj any) {
			item, ok := informerItemFromObject(schemaGVR, gvr.Kind, generator, obj, false)
			if ok {
				queue.Add(item)
			}
		},
		DeleteFunc: func(obj any) {
			item, ok := informerItemFromObject(schemaGVR, gvr.Kind, generator, obj, true)
			if ok {
				queue.Add(item)
			}
		},
	})
	if err != nil {
		return fmt.Errorf("register handler for %s: %w", schemaGVR, err)
	}

	go informer.Run(stop)
	return nil
}

// StopWatch tears down the informer for the given GVR. Safe to call for GVRs
// that are not registered.
func (r *GeneratedResourceReconciler) StopWatch(gvr GeneratedGVR) {
	schemaGVR := schema.GroupVersionResource{
		Group:    gvr.Group,
		Version:  gvr.Version,
		Resource: gvr.Resource,
	}
	r.mu.Lock()
	entry, exists := r.watches[schemaGVR]
	delete(r.watches, schemaGVR)
	r.mu.Unlock()
	if exists {
		close(entry.stop)
	}
}

func informerItemFromObject(
	gvr schema.GroupVersionResource,
	kind string,
	generator types.NamespacedName,
	obj any,
	isDelete bool,
) (generatedWorkItem, bool) {
	if isDelete {
		if tombstone, ok := obj.(cache.DeletedFinalStateUnknown); ok {
			if unstr, ok := tombstone.Obj.(*unstructured.Unstructured); ok {
				return generatedWorkItem{
					GVR:       gvr,
					Kind:      kind,
					Key:       keyFor(unstr),
					Generator: generator,
					IsDelete:  true,
					Tombstone: unstr.DeepCopy(),
				}, true
			}
			return generatedWorkItem{}, false
		}
	}
	unstr, ok := obj.(*unstructured.Unstructured)
	if !ok {
		return generatedWorkItem{}, false
	}
	return generatedWorkItem{
		GVR:       gvr,
		Kind:      kind,
		Key:       keyFor(unstr),
		Generator: generator,
		IsDelete:  isDelete,
	}, true
}

func keyFor(obj *unstructured.Unstructured) string {
	if obj.GetNamespace() == "" {
		return obj.GetName()
	}
	return obj.GetNamespace() + "/" + obj.GetName()
}

func (r *GeneratedResourceReconciler) worker(ctx context.Context) {
	logger := ctrllog.FromContext(ctx).WithName("generated-resource-worker")
	for {
		item, shutdown := r.queue.Get()
		if shutdown {
			return
		}
		func() {
			defer r.queue.Done(item)
			if err := r.reconcile(ctx, item); err != nil {
				logger.Error(err, "reconcile generated resource", generatedResourceStatusLogKey, item.Key, "gvr", item.GVR)
				r.queue.AddRateLimited(item)
				return
			}
			r.queue.Forget(item)
		}()
	}
}

func (r *GeneratedResourceReconciler) reconcile(ctx context.Context, item generatedWorkItem) error {
	logger := ctrllog.FromContext(ctx).WithValues(generatedResourceStatusLogKey, item.Key, "gvr", item.GVR)

	generator := &declarestv1alpha1.CRDGenerator{}
	if err := r.Client.Get(ctx, item.Generator, generator); err != nil {
		if apierrors.IsNotFound(err) {
			// Parent gone — index cleanup handled by CRDGenerator finalizer.
			return nil
		}
		return err
	}

	version := selectCRDGeneratorVersion(generator, item.GVR.Version)
	if version == nil {
		logger.Info("generator version missing; skipping", "version", item.GVR.Version)
		return nil
	}

	if item.IsDelete {
		return r.handleDelete(ctx, generator, version, item)
	}

	namespace, name := splitKey(item.Key)
	obj := &unstructured.Unstructured{}
	obj.SetGroupVersionKind(schema.GroupVersionKind{Group: item.GVR.Group, Version: item.GVR.Version, Kind: item.Kind})
	if err := r.Client.Get(ctx, types.NamespacedName{Namespace: namespace, Name: name}, obj); err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return err
	}

	// Ensure origin annotation so the finalizer can read parent coordinates
	// even if the parent CRDGenerator has been deleted.
	if err := r.ensureOriginAnnotation(ctx, obj, generator); err != nil {
		return err
	}

	logicalPath := logicalPathForGeneratedCR(version.CollectionPath, obj)
	managedServiceRef, _, _ := unstructured.NestedString(obj.Object, "spec", "managedServiceRef", "name")
	managedServiceRef = strings.TrimSpace(managedServiceRef)

	if r.Conflicts != nil && managedServiceRef != "" {
		r.Conflicts.Register(
			obj.GetNamespace(),
			managedServiceRef,
			version.CollectionPath,
			logicalPath,
			"",
			ConflictSource{
				CRDGeneratorNamespace: generator.Namespace,
				CRDGeneratorName:      generator.Name,
				GeneratedKind:         item.Kind,
				LogicalPath:           logicalPath,
			},
		)
	}

	// Placeholder for Apply-orchestration. Delegating to `orchestrator.Apply`
	// here requires wiring a Session against the referenced ManagedService,
	// which is the responsibility of a dedicated follow-up. For v1alpha1 the
	// reconciler emits a success event and marks the CR as observed; future
	// work replaces this block with the real HTTP mutation call.
	if err := r.markObserved(ctx, obj); err != nil {
		return err
	}
	emitEventf(r.Recorder, obj, corev1.EventTypeNormal, generatedResourceReasonSyncSuccess,
		"generated resource observed (managedServiceRef=%s logicalPath=%s)", managedServiceRef, logicalPath)
	return nil
}

func (r *GeneratedResourceReconciler) handleDelete(
	ctx context.Context,
	generator *declarestv1alpha1.CRDGenerator,
	_ *declarestv1alpha1.CRDGeneratorVersion,
	item generatedWorkItem,
) error {
	if r.Conflicts != nil {
		logicalPath := ""
		if item.Tombstone != nil {
			logicalPath = logicalPathForGeneratedCR("", item.Tombstone)
		}
		r.Conflicts.Unregister(generator.Namespace, generator.Name, logicalPath)
	}
	return nil
}

func (r *GeneratedResourceReconciler) ensureOriginAnnotation(
	ctx context.Context,
	obj *unstructured.Unstructured,
	generator *declarestv1alpha1.CRDGenerator,
) error {
	annotations := obj.GetAnnotations()
	coords := fmt.Sprintf("%s/%s", generator.Namespace, generator.Name)
	if annotations[generatedResourceOriginAnnotation] == coords {
		return nil
	}
	if annotations == nil {
		annotations = map[string]string{}
	}
	annotations[generatedResourceOriginAnnotation] = coords
	obj.SetAnnotations(annotations)
	return r.Client.Update(ctx, obj)
}

func (r *GeneratedResourceReconciler) markObserved(ctx context.Context, obj *unstructured.Unstructured) error {
	now := metav1.NewTime(time.Now().UTC())
	if err := unstructured.SetNestedField(obj.Object, now.UTC().Format(time.RFC3339), "status", "lastAppliedTime"); err != nil {
		return err
	}
	if err := unstructured.SetNestedField(obj.Object, int64(obj.GetGeneration()), "status", "observedGeneration"); err != nil {
		return err
	}
	return r.Client.Status().Update(ctx, obj)
}

func splitKey(key string) (string, string) {
	parts := strings.SplitN(key, "/", 2)
	if len(parts) == 1 {
		return "", parts[0]
	}
	return parts[0], parts[1]
}

func selectCRDGeneratorVersion(generator *declarestv1alpha1.CRDGenerator, name string) *declarestv1alpha1.CRDGeneratorVersion {
	for idx := range generator.Spec.Versions {
		if generator.Spec.Versions[idx].Name == name {
			return &generator.Spec.Versions[idx]
		}
	}
	return nil
}

func logicalPathForGeneratedCR(collectionPath string, obj *unstructured.Unstructured) string {
	name := strings.TrimSpace(obj.GetName())
	if name == "" {
		return ""
	}
	trimmedCollection := strings.Trim(strings.TrimSpace(collectionPath), "/")
	if trimmedCollection == "" {
		return "/" + name
	}
	return "/" + trimmedCollection + "/" + name
}
