// Copyright 2026 Carlos Marques
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package controllers

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	declarestv1alpha1 "github.com/crmarques/declarest/api/v1alpha1"
	"github.com/crmarques/declarest/config"
	"github.com/crmarques/declarest/faults"
	mutateapp "github.com/crmarques/declarest/internal/app/resource/mutate"
	"github.com/crmarques/declarest/internal/bootstrap"
	orchestratordomain "github.com/crmarques/declarest/orchestrator"
	"github.com/crmarques/declarest/resource"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/dynamic/dynamicinformer"
	"k8s.io/client-go/tools/cache"
	k8sevents "k8s.io/client-go/tools/events"
	"k8s.io/client-go/util/workqueue"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

const (
	generatedResourceResyncInterval       = 10 * time.Minute
	defaultGeneratedResourceWorkerCount   = 2
	generatedResourceStatusLogKey         = "generatedResource"
	generatedResourceOriginAnnotation     = declarestv1alpha1.CRDGeneratorOwnerAnnotation
	generatedResourceReasonSyncSuccess    = "Applied"
	generatedResourceReasonSyncFailed     = "ApplyFailed"
	generatedResourceReasonFinalized      = "Finalized"
	generatedResourceDeletionPolicyOrphan = "Orphan"
	generatedResourceDeletionPolicyDelete = "Delete"
)

type generatedSessionBuilder func(config.Context) (bootstrap.Session, error)

type generatedMutationExecutor func(context.Context, mutateapp.Dependencies, mutateapp.Request) (mutateapp.Result, error)

// GeneratedResourceReconciler is a metacontroller that reconciles instances of
// any CRD generated by a CRDGenerator. It uses a single
// `dynamicinformer.DynamicSharedInformerFactory` shared across all generated
// GVRs; CRDGeneratorReconciler calls EnsureWatch / StopWatch to drive the
// factory as CRDs are created or removed.
type GeneratedResourceReconciler struct {
	manager.Runnable

	Client        client.Client
	DynamicClient dynamic.Interface
	Recorder      k8sevents.EventRecorder
	Conflicts     *ConflictIndex
	WorkerCount   int

	SessionBuilder   generatedSessionBuilder
	MutationExecutor generatedMutationExecutor

	factory dynamicinformer.DynamicSharedInformerFactory

	mu      sync.Mutex
	watches map[schema.GroupVersionResource]generatedWatchEntry
	queue   workqueue.TypedRateLimitingInterface[generatedWorkItem]
	started bool
	stopCh  chan struct{}
}

type generatedWatchEntry struct {
	generator types.NamespacedName
	kind      string
	stop      chan struct{}
}

type generatedWorkItem struct {
	GVR       schema.GroupVersionResource
	Kind      string
	Key       string // namespace/name
	Generator types.NamespacedName
	IsDelete  bool
	Tombstone *unstructured.Unstructured
}

// NewGeneratedResourceReconciler returns an initialised reconciler suitable for
// Manager.Add.
func NewGeneratedResourceReconciler(
	kubeClient client.Client,
	dynamicClient dynamic.Interface,
	recorder k8sevents.EventRecorder,
	conflicts *ConflictIndex,
	workerCount int,
) *GeneratedResourceReconciler {
	if workerCount < 1 {
		workerCount = defaultGeneratedResourceWorkerCount
	}
	return &GeneratedResourceReconciler{
		Client:           kubeClient,
		DynamicClient:    dynamicClient,
		Recorder:         recorder,
		Conflicts:        conflicts,
		WorkerCount:      workerCount,
		SessionBuilder:   bootstrap.NewSessionFromResolvedContext,
		MutationExecutor: mutateapp.Execute,
		watches:          make(map[schema.GroupVersionResource]generatedWatchEntry),
		stopCh:           make(chan struct{}),
	}
}

// Start satisfies manager.Runnable. It boots the shared workqueue and blocks
// until ctx is cancelled.
func (r *GeneratedResourceReconciler) Start(ctx context.Context) error {
	r.mu.Lock()
	r.queue = workqueue.NewTypedRateLimitingQueue(workqueue.DefaultTypedControllerRateLimiter[generatedWorkItem]())
	r.factory = dynamicinformer.NewDynamicSharedInformerFactory(r.DynamicClient, generatedResourceResyncInterval)
	r.started = true
	r.mu.Unlock()

	workerCount := r.WorkerCount
	if workerCount < 1 {
		workerCount = defaultGeneratedResourceWorkerCount
	}
	for i := 0; i < workerCount; i++ {
		go r.worker(ctx)
	}

	<-ctx.Done()

	r.mu.Lock()
	r.queue.ShutDown()
	r.factory.Shutdown()
	close(r.stopCh)
	r.mu.Unlock()
	return nil
}

// EnsureWatch registers a dynamic informer for the given GVR if one does not
// already exist. Idempotent.
func (r *GeneratedResourceReconciler) EnsureWatch(gvr GeneratedGVR, generator types.NamespacedName) error {
	schemaGVR := schema.GroupVersionResource{
		Group:    gvr.Group,
		Version:  gvr.Version,
		Resource: gvr.Resource,
	}

	r.mu.Lock()
	if !r.started {
		r.mu.Unlock()
		return fmt.Errorf("generated resource reconciler is not started")
	}
	if _, exists := r.watches[schemaGVR]; exists {
		r.mu.Unlock()
		return nil
	}
	stop := make(chan struct{})
	r.watches[schemaGVR] = generatedWatchEntry{generator: generator, kind: gvr.Kind, stop: stop}
	factory := r.factory
	queue := r.queue
	r.mu.Unlock()

	informer := factory.ForResource(schemaGVR).Informer()
	_, err := informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj any) {
			item, ok := informerItemFromObject(schemaGVR, gvr.Kind, generator, obj, false)
			if ok {
				queue.Add(item)
			}
		},
		UpdateFunc: func(oldObj, newObj any) {
			item, ok := informerItemFromUpdate(schemaGVR, gvr.Kind, generator, oldObj, newObj)
			if ok {
				queue.Add(item)
			}
		},
		DeleteFunc: func(obj any) {
			item, ok := informerItemFromObject(schemaGVR, gvr.Kind, generator, obj, true)
			if ok {
				queue.Add(item)
			}
		},
	})
	if err != nil {
		return fmt.Errorf("register handler for %s: %w", schemaGVR, err)
	}

	if err := r.enqueueExistingGeneratedResources(context.Background(), schemaGVR, gvr, generator, queue); err != nil {
		close(stop)
		return err
	}

	go informer.Run(stop)
	return nil
}

// StopWatch tears down the informer for the given GVR. Safe to call for GVRs
// that are not registered.
func (r *GeneratedResourceReconciler) StopWatch(gvr GeneratedGVR) {
	schemaGVR := schema.GroupVersionResource{
		Group:    gvr.Group,
		Version:  gvr.Version,
		Resource: gvr.Resource,
	}
	r.mu.Lock()
	entry, exists := r.watches[schemaGVR]
	delete(r.watches, schemaGVR)
	r.mu.Unlock()
	if exists {
		close(entry.stop)
	}
}

func informerItemFromObject(
	gvr schema.GroupVersionResource,
	kind string,
	generator types.NamespacedName,
	obj any,
	isDelete bool,
) (generatedWorkItem, bool) {
	if isDelete {
		if tombstone, ok := obj.(cache.DeletedFinalStateUnknown); ok {
			if unstr, ok := tombstone.Obj.(*unstructured.Unstructured); ok {
				return generatedWorkItem{
					GVR:       gvr,
					Kind:      kind,
					Key:       keyFor(unstr),
					Generator: generator,
					IsDelete:  true,
					Tombstone: unstr.DeepCopy(),
				}, true
			}
			return generatedWorkItem{}, false
		}
	}
	unstr, ok := obj.(*unstructured.Unstructured)
	if !ok {
		return generatedWorkItem{}, false
	}
	return generatedWorkItem{
		GVR:       gvr,
		Kind:      kind,
		Key:       keyFor(unstr),
		Generator: generator,
		IsDelete:  isDelete,
	}, true
}

func informerItemFromUpdate(
	gvr schema.GroupVersionResource,
	kind string,
	generator types.NamespacedName,
	oldObj any,
	newObj any,
) (generatedWorkItem, bool) {
	oldUnstructured, oldOK := oldObj.(*unstructured.Unstructured)
	newUnstructured, newOK := newObj.(*unstructured.Unstructured)
	if !newOK {
		return generatedWorkItem{}, false
	}
	if oldOK &&
		oldUnstructured.GetGeneration() == newUnstructured.GetGeneration() &&
		oldUnstructured.GetDeletionTimestamp().IsZero() == newUnstructured.GetDeletionTimestamp().IsZero() {
		return generatedWorkItem{}, false
	}
	return informerItemFromObject(gvr, kind, generator, newObj, false)
}

func (r *GeneratedResourceReconciler) enqueueExistingGeneratedResources(
	ctx context.Context,
	schemaGVR schema.GroupVersionResource,
	gvr GeneratedGVR,
	generator types.NamespacedName,
	queue workqueue.TypedRateLimitingInterface[generatedWorkItem],
) error {
	if r.DynamicClient == nil {
		return nil
	}
	var resourceClient dynamic.ResourceInterface = r.DynamicClient.Resource(schemaGVR)
	if gvr.Scope == declarestv1alpha1.CRDGeneratorScopeNamespaced {
		resourceClient = r.DynamicClient.Resource(schemaGVR).Namespace(metav1.NamespaceAll)
	}
	list, err := resourceClient.List(ctx, metav1.ListOptions{})
	if err != nil {
		return fmt.Errorf("list existing generated resources for %s: %w", schemaGVR, err)
	}
	for idx := range list.Items {
		item, ok := informerItemFromObject(schemaGVR, gvr.Kind, generator, &list.Items[idx], false)
		if ok {
			queue.Add(item)
		}
	}
	return nil
}

func keyFor(obj *unstructured.Unstructured) string {
	if obj.GetNamespace() == "" {
		return obj.GetName()
	}
	return obj.GetNamespace() + "/" + obj.GetName()
}

func (r *GeneratedResourceReconciler) worker(ctx context.Context) {
	logger := ctrllog.FromContext(ctx).WithName("generated-resource-worker")
	for {
		item, shutdown := r.queue.Get()
		if shutdown {
			return
		}
		func() {
			defer r.queue.Done(item)
			if err := r.reconcile(ctx, item); err != nil {
				logger.Error(err, "reconcile generated resource", generatedResourceStatusLogKey, item.Key, "gvr", item.GVR)
				r.queue.AddRateLimited(item)
				return
			}
			r.queue.Forget(item)
		}()
	}
}

func (r *GeneratedResourceReconciler) reconcile(ctx context.Context, item generatedWorkItem) error {
	logger := ctrllog.FromContext(ctx).WithValues(generatedResourceStatusLogKey, item.Key, "gvr", item.GVR)

	generator := &declarestv1alpha1.CRDGenerator{}
	if err := r.Client.Get(ctx, item.Generator, generator); err != nil {
		if apierrors.IsNotFound(err) {
			// Parent gone — index cleanup handled by CRDGenerator finalizer.
			return nil
		}
		return err
	}

	version := selectCRDGeneratorVersion(generator, item.GVR.Version)
	if version == nil {
		logger.Info("generator version missing; skipping", "version", item.GVR.Version)
		return nil
	}

	if item.IsDelete {
		return r.handleDelete(generator, version, item)
	}

	namespace, name := splitKey(item.Key)
	obj := &unstructured.Unstructured{}
	obj.SetGroupVersionKind(schema.GroupVersionKind{Group: item.GVR.Group, Version: item.GVR.Version, Kind: item.Kind})
	if err := r.Client.Get(ctx, types.NamespacedName{Namespace: namespace, Name: name}, obj); err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return err
	}
	if !obj.GetDeletionTimestamp().IsZero() {
		return r.finalizeGeneratedResource(ctx, generator, version, obj)
	}

	if err := r.ensureGeneratedResourceMetadata(ctx, obj, generator); err != nil {
		return err
	}

	collectionPath, logicalPath, pathErr := generatedResourcePaths(version, obj)
	if pathErr != nil {
		_ = r.markGeneratedResourceFailed(ctx, obj, conditionReasonSpecInvalid, pathErr.Error())
		return pathErr
	}
	managedServiceNamespace := generatedResourceReferenceNamespace(generator, obj)
	managedServiceRef, refErr := generatedResourceManagedServiceName(obj)
	if refErr != nil {
		_ = r.markGeneratedResourceFailed(ctx, obj, conditionReasonDependencyInvalid, refErr.Error())
		return refErr
	}

	r.unregisterPreviousGeneratedResourceOwnership(generator, obj)
	if r.Conflicts != nil && managedServiceRef != "" {
		r.Conflicts.Register(
			managedServiceNamespace,
			managedServiceRef,
			collectionPath,
			logicalPath,
			"",
			ConflictSource{
				CRDGeneratorNamespace: generator.Namespace,
				CRDGeneratorName:      generator.Name,
				GeneratedKind:         item.Kind,
				LogicalPath:           logicalPath,
			},
		)
	}

	applied, applyErr := r.applyGeneratedResource(ctx, generator, version, obj, managedServiceNamespace, managedServiceRef, collectionPath, logicalPath)
	if applyErr != nil {
		_ = r.markGeneratedResourceFailed(ctx, obj, generatedResourceReasonSyncFailed, applyErr.Error())
		emitEventf(r.Recorder, obj, corev1.EventTypeWarning, generatedResourceReasonSyncFailed,
			"generated resource apply failed (managedServiceRef=%s logicalPath=%s): %v", managedServiceRef, logicalPath, applyErr)
		return applyErr
	}

	remoteID := strings.TrimSpace(applied.RemoteID)
	if r.Conflicts != nil && remoteID != "" {
		r.Conflicts.Register(
			managedServiceNamespace,
			managedServiceRef,
			collectionPath,
			logicalPath,
			remoteID,
			ConflictSource{
				CRDGeneratorNamespace: generator.Namespace,
				CRDGeneratorName:      generator.Name,
				GeneratedKind:         item.Kind,
				LogicalPath:           logicalPath,
				RemoteID:              remoteID,
			},
		)
	}
	if err := r.patchGeneratedResourceOwnership(ctx, obj, generator, managedServiceNamespace, managedServiceRef, collectionPath, logicalPath, remoteID); err != nil {
		return err
	}
	if err := r.markGeneratedResourceApplied(ctx, obj, applied); err != nil {
		return err
	}
	emitEventf(r.Recorder, obj, corev1.EventTypeNormal, generatedResourceReasonSyncSuccess,
		"generated resource applied (managedServiceRef=%s logicalPath=%s remoteID=%s)", managedServiceRef, logicalPath, remoteID)
	return nil
}

func (r *GeneratedResourceReconciler) handleDelete(
	generator *declarestv1alpha1.CRDGenerator,
	_ *declarestv1alpha1.CRDGeneratorVersion,
	item generatedWorkItem,
) error {
	if r.Conflicts != nil {
		logicalPath := ""
		if item.Tombstone != nil {
			logicalPath = generatedResourceAnnotation(item.Tombstone, declarestv1alpha1.GeneratedResourceLogicalPathAnnotation)
			if logicalPath == "" {
				logicalPath = logicalPathForGeneratedCR("", item.Tombstone)
			}
		}
		r.Conflicts.Unregister(generator.Namespace, generator.Name, logicalPath)
	}
	return nil
}

func (r *GeneratedResourceReconciler) ensureGeneratedResourceMetadata(
	ctx context.Context,
	obj *unstructured.Unstructured,
	generator *declarestv1alpha1.CRDGenerator,
) error {
	changed := false
	original := obj.DeepCopy()
	annotations := obj.GetAnnotations()
	coords := fmt.Sprintf("%s/%s", generator.Namespace, generator.Name)
	if annotations == nil {
		annotations = map[string]string{}
	}
	if annotations[generatedResourceOriginAnnotation] != coords {
		annotations[generatedResourceOriginAnnotation] = coords
		changed = true
	}
	obj.SetAnnotations(annotations)
	if !controllerutil.ContainsFinalizer(obj, finalizerName) {
		controllerutil.AddFinalizer(obj, finalizerName)
		changed = true
	}
	if !changed {
		return nil
	}
	if err := r.Client.Patch(ctx, obj, client.MergeFrom(original)); err != nil {
		return err
	}
	return r.Client.Get(ctx, client.ObjectKeyFromObject(obj), obj)
}

func (r *GeneratedResourceReconciler) unregisterPreviousGeneratedResourceOwnership(
	generator *declarestv1alpha1.CRDGenerator,
	obj *unstructured.Unstructured,
) {
	if r.Conflicts == nil || generator == nil || obj == nil {
		return
	}
	previousPath := generatedResourceAnnotation(obj, declarestv1alpha1.GeneratedResourceLogicalPathAnnotation)
	if previousPath == "" {
		return
	}
	r.Conflicts.Unregister(generator.Namespace, generator.Name, previousPath)
}

func (r *GeneratedResourceReconciler) applyGeneratedResource(
	ctx context.Context,
	generator *declarestv1alpha1.CRDGenerator,
	version *declarestv1alpha1.CRDGeneratorVersion,
	obj *unstructured.Unstructured,
	managedServiceNamespace string,
	managedServiceName string,
	collectionPath string,
	logicalPath string,
) (resource.Resource, error) {
	managedService, err := r.loadGeneratedManagedService(ctx, managedServiceNamespace, managedServiceName)
	if err != nil {
		return resource.Resource{}, err
	}
	secretStore, err := r.loadGeneratedSecretStore(ctx, managedServiceNamespace, obj)
	if err != nil {
		return resource.Resource{}, err
	}
	runtimeBuild, err := buildGeneratedResourceRuntimeContext(ctx, r.Client, generator, version, managedServiceNamespace, obj.GetName(), managedService, secretStore)
	if err != nil {
		return resource.Resource{}, err
	}
	if runtimeBuild.Cleanup != nil {
		defer runtimeBuild.Cleanup()
	}
	sessionBuilder := r.SessionBuilder
	if sessionBuilder == nil {
		sessionBuilder = bootstrap.NewSessionFromResolvedContext
	}
	session, err := sessionBuilder(runtimeBuild.ResolvedContext)
	if err != nil {
		return resource.Resource{}, err
	}
	payload, found, err := unstructured.NestedFieldNoCopy(obj.Object, "spec", "payload")
	if err != nil {
		return resource.Resource{}, err
	}
	if !found {
		return resource.Resource{}, fmt.Errorf("spec.payload is required")
	}
	mutationExecutor := r.MutationExecutor
	if mutationExecutor == nil {
		mutationExecutor = mutateapp.Execute
	}
	deps := mutateapp.Dependencies{Orchestrator: session.Orchestrator}
	if session.Services != nil {
		deps.Metadata = session.Services.MetadataService()
		deps.Secrets = session.Services.SecretProvider()
	}
	result, err := mutationExecutor(ctx, deps, mutateapp.Request{
		Operation:        mutateapp.OperationApply,
		LogicalPath:      logicalPath,
		Force:            false,
		Value:            resource.Content{Value: resource.DeepCopyValue(payload), Descriptor: resource.NormalizePayloadDescriptor(resource.PayloadDescriptor{PayloadType: resource.PayloadTypeJSON})},
		HasExplicitInput: true,
		RefreshLocal:     false,
	})
	if err != nil {
		return resource.Resource{}, err
	}
	if len(result.Items) == 0 {
		return resource.Resource{LogicalPath: logicalPath, CollectionPath: collectionPath}, nil
	}
	return result.Items[0], nil
}

func (r *GeneratedResourceReconciler) loadGeneratedManagedService(
	ctx context.Context,
	namespace string,
	name string,
) (*declarestv1alpha1.ManagedService, error) {
	managedService := &declarestv1alpha1.ManagedService{}
	if err := r.Client.Get(ctx, types.NamespacedName{Namespace: namespace, Name: name}, managedService); err != nil {
		return nil, err
	}
	managedService = expandRuntimeManagedService(managedService)
	managedService.Default()
	if err := managedService.ValidateSpec(); err != nil {
		return nil, fmt.Errorf("invalid referenced managed service: %w", err)
	}
	return managedService, nil
}

func (r *GeneratedResourceReconciler) loadGeneratedSecretStore(
	ctx context.Context,
	namespace string,
	obj *unstructured.Unstructured,
) (*declarestv1alpha1.SecretStore, error) {
	name, _, _ := unstructured.NestedString(obj.Object, "spec", "secretStoreRef", "name")
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, nil
	}
	secretStore := &declarestv1alpha1.SecretStore{}
	if err := r.Client.Get(ctx, types.NamespacedName{Namespace: namespace, Name: name}, secretStore); err != nil {
		return nil, err
	}
	secretStore = expandRuntimeSecretStore(secretStore)
	if err := secretStore.ValidateSpec(); err != nil {
		return nil, fmt.Errorf("invalid referenced secret store: %w", err)
	}
	return secretStore, nil
}

func (r *GeneratedResourceReconciler) finalizeGeneratedResource(
	ctx context.Context,
	generator *declarestv1alpha1.CRDGenerator,
	version *declarestv1alpha1.CRDGeneratorVersion,
	obj *unstructured.Unstructured,
) error {
	if !controllerutil.ContainsFinalizer(obj, finalizerName) {
		return nil
	}
	collectionPath, logicalPath, pathErr := generatedResourcePaths(version, obj)
	if pathErr != nil {
		logicalPath = generatedResourceAnnotation(obj, declarestv1alpha1.GeneratedResourceLogicalPathAnnotation)
	}
	if generatedResourceDeletionPolicy(obj) == generatedResourceDeletionPolicyDelete {
		managedServiceNamespace := generatedResourceReferenceNamespace(generator, obj)
		managedServiceRef, refErr := generatedResourceManagedServiceName(obj)
		if refErr != nil {
			return refErr
		}
		managedService, err := r.loadGeneratedManagedService(ctx, managedServiceNamespace, managedServiceRef)
		if err != nil {
			return err
		}
		secretStore, err := r.loadGeneratedSecretStore(ctx, managedServiceNamespace, obj)
		if err != nil {
			return err
		}
		runtimeBuild, err := buildGeneratedResourceRuntimeContext(ctx, r.Client, generator, version, managedServiceNamespace, obj.GetName(), managedService, secretStore)
		if err != nil {
			return err
		}
		if runtimeBuild.Cleanup != nil {
			defer runtimeBuild.Cleanup()
		}
		sessionBuilder := r.SessionBuilder
		if sessionBuilder == nil {
			sessionBuilder = bootstrap.NewSessionFromResolvedContext
		}
		session, err := sessionBuilder(runtimeBuild.ResolvedContext)
		if err != nil {
			return err
		}
		if err := session.Orchestrator.Delete(ctx, logicalPath, orchestratordomain.DeletePolicy{}); err != nil && !faults.IsCategory(err, faults.NotFoundError) {
			return err
		}
		emitEventf(r.Recorder, obj, corev1.EventTypeNormal, generatedResourceReasonFinalized,
			"deleted remote resource (logicalPath=%s collectionPath=%s)", logicalPath, collectionPath)
	}
	if r.Conflicts != nil {
		r.Conflicts.Unregister(generator.Namespace, generator.Name, logicalPath)
	}
	original := obj.DeepCopy()
	controllerutil.RemoveFinalizer(obj, finalizerName)
	return r.Client.Patch(ctx, obj, client.MergeFrom(original))
}

func (r *GeneratedResourceReconciler) patchGeneratedResourceOwnership(
	ctx context.Context,
	obj *unstructured.Unstructured,
	generator *declarestv1alpha1.CRDGenerator,
	managedServiceNamespace string,
	managedServiceName string,
	collectionPath string,
	logicalPath string,
	remoteID string,
) error {
	annotations := obj.GetAnnotations()
	if annotations == nil {
		annotations = map[string]string{}
	}
	desired := map[string]string{
		generatedResourceOriginAnnotation:                           fmt.Sprintf("%s/%s", generator.Namespace, generator.Name),
		declarestv1alpha1.GeneratedResourceManagedServiceAnnotation: fmt.Sprintf("%s/%s", managedServiceNamespace, managedServiceName),
		declarestv1alpha1.GeneratedResourceCollectionPathAnnotation: collectionPath,
		declarestv1alpha1.GeneratedResourceLogicalPathAnnotation:    logicalPath,
		declarestv1alpha1.GeneratedResourceRemoteIDAnnotation:       remoteID,
	}
	changed := false
	for key, value := range desired {
		if value == "" {
			if _, exists := annotations[key]; exists {
				delete(annotations, key)
				changed = true
			}
			continue
		}
		if annotations[key] != value {
			annotations[key] = value
			changed = true
		}
	}
	if !changed {
		return nil
	}
	original := obj.DeepCopy()
	obj.SetAnnotations(annotations)
	if err := r.Client.Patch(ctx, obj, client.MergeFrom(original)); err != nil {
		return err
	}
	return r.Client.Get(ctx, client.ObjectKeyFromObject(obj), obj)
}

func (r *GeneratedResourceReconciler) markGeneratedResourceApplied(ctx context.Context, obj *unstructured.Unstructured, applied resource.Resource) error {
	now := metav1.NewTime(time.Now().UTC())
	if err := unstructured.SetNestedField(obj.Object, now.UTC().Format(time.RFC3339), "status", "lastAppliedTime"); err != nil {
		return err
	}
	if err := unstructured.SetNestedField(obj.Object, obj.GetGeneration(), "status", "observedGeneration"); err != nil {
		return err
	}
	if err := unstructured.SetNestedField(obj.Object, strings.TrimSpace(applied.RemoteID), "status", "remoteID"); err != nil {
		return err
	}
	if err := unstructured.SetNestedField(obj.Object, strings.TrimSpace(obj.GetResourceVersion()), "status", "lastAppliedRevision"); err != nil {
		return err
	}
	setGeneratedResourceCondition(obj, declarestv1alpha1.ConditionTypeReady, metav1.ConditionTrue, conditionReasonReady, "generated resource applied")
	setGeneratedResourceCondition(obj, declarestv1alpha1.ConditionTypeStalled, metav1.ConditionFalse, conditionReasonReady, "")
	return r.Client.Status().Update(ctx, obj)
}

func (r *GeneratedResourceReconciler) markGeneratedResourceFailed(ctx context.Context, obj *unstructured.Unstructured, reason string, message string) error {
	if err := unstructured.SetNestedField(obj.Object, obj.GetGeneration(), "status", "observedGeneration"); err != nil {
		return err
	}
	setGeneratedResourceCondition(obj, declarestv1alpha1.ConditionTypeReady, metav1.ConditionFalse, reason, message)
	setGeneratedResourceCondition(obj, declarestv1alpha1.ConditionTypeStalled, metav1.ConditionTrue, reason, message)
	return r.Client.Status().Update(ctx, obj)
}

func setGeneratedResourceCondition(obj *unstructured.Unstructured, conditionType string, status metav1.ConditionStatus, reason string, message string) {
	conditions, _, _ := unstructured.NestedSlice(obj.Object, "status", "conditions")
	nowValue := metav1.Now().UTC().Format(time.RFC3339)
	condition := map[string]any{
		"type":               conditionType,
		"status":             string(status),
		"reason":             strings.TrimSpace(reason),
		"message":            strings.TrimSpace(message),
		"lastTransitionTime": nowValue,
	}
	replaced := false
	for idx := range conditions {
		existing, ok := conditions[idx].(map[string]any)
		if !ok || existing["type"] != conditionType {
			continue
		}
		if existing["status"] == string(status) {
			if value, ok := existing["lastTransitionTime"].(string); ok && strings.TrimSpace(value) != "" {
				condition["lastTransitionTime"] = value
			}
		}
		conditions[idx] = condition
		replaced = true
		break
	}
	if !replaced {
		conditions = append(conditions, condition)
	}
	_ = unstructured.SetNestedSlice(obj.Object, conditions, "status", "conditions")
}

func splitKey(key string) (string, string) {
	parts := strings.SplitN(key, "/", 2)
	if len(parts) == 1 {
		return "", parts[0]
	}
	return parts[0], parts[1]
}

func selectCRDGeneratorVersion(generator *declarestv1alpha1.CRDGenerator, name string) *declarestv1alpha1.CRDGeneratorVersion {
	for idx := range generator.Spec.Versions {
		if generator.Spec.Versions[idx].Name == name {
			return &generator.Spec.Versions[idx]
		}
	}
	return nil
}

func generatedResourceReferenceNamespace(generator *declarestv1alpha1.CRDGenerator, obj *unstructured.Unstructured) string {
	if namespace := strings.TrimSpace(obj.GetNamespace()); namespace != "" {
		return namespace
	}
	if generator == nil {
		return ""
	}
	return strings.TrimSpace(generator.Namespace)
}

func generatedResourceManagedServiceName(obj *unstructured.Unstructured) (string, error) {
	managedServiceRef, _, _ := unstructured.NestedString(obj.Object, "spec", "managedServiceRef", "name")
	managedServiceRef = strings.TrimSpace(managedServiceRef)
	if managedServiceRef == "" {
		return "", fmt.Errorf("spec.managedServiceRef.name is required")
	}
	return managedServiceRef, nil
}

func generatedResourceDeletionPolicy(obj *unstructured.Unstructured) string {
	value, _, _ := unstructured.NestedString(obj.Object, "spec", "deletionPolicy")
	value = strings.TrimSpace(value)
	if value == "" {
		return generatedResourceDeletionPolicyOrphan
	}
	return value
}

func generatedResourcePaths(version *declarestv1alpha1.CRDGeneratorVersion, obj *unstructured.Unstructured) (string, string, error) {
	collectionPath := ""
	if version != nil {
		collectionPath = version.CollectionPath
	}
	if override, _, _ := unstructured.NestedString(obj.Object, "spec", "collectionPathOverride"); strings.TrimSpace(override) != "" {
		collectionPath = override
	}
	collectionPath, err := normalizeGeneratedResourcePath(collectionPath)
	if err != nil {
		return "", "", fmt.Errorf("collection path is invalid: %w", err)
	}
	name := strings.TrimSpace(obj.GetName())
	if name == "" {
		return "", "", fmt.Errorf("metadata.name is required")
	}
	return collectionPath, logicalPathForGeneratedCR(collectionPath, obj), nil
}

func normalizeGeneratedResourcePath(raw string) (string, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return "/", nil
	}
	if !strings.HasPrefix(value, "/") {
		value = "/" + value
	}
	return resource.NormalizeLogicalPath(value)
}

func generatedResourceAnnotation(obj *unstructured.Unstructured, key string) string {
	if obj == nil {
		return ""
	}
	return strings.TrimSpace(obj.GetAnnotations()[key])
}

func logicalPathForGeneratedCR(collectionPath string, obj *unstructured.Unstructured) string {
	name := strings.TrimSpace(obj.GetName())
	if name == "" {
		return ""
	}
	trimmedCollection := strings.Trim(strings.TrimSpace(collectionPath), "/")
	if trimmedCollection == "" {
		return "/" + name
	}
	return "/" + trimmedCollection + "/" + name
}
