version: 2

project_name: declarest

builds:
  - id: declarest
    main: ./cli
    binary: declarest
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X declarest/cli/cmd.Version={{.Version}}
      - -X declarest/cli/cmd.Commit={{.Commit}}
      - -X declarest/cli/cmd.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  use: github
