# syntax=docker/dockerfile:1.7

ARG GO_VERSION
FROM golang:${GO_VERSION} AS builder
WORKDIR /src
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w" -o /out/manager ./cmd/declarest-operator-manager

FROM gcr.io/distroless/static-debian13:nonroot
WORKDIR /
COPY --from=builder /out/manager /manager
USER 65532:65532
ENTRYPOINT ["/manager"]
