# syntax=docker/dockerfile:1.7

FROM golang:1.25 AS builder
WORKDIR /workspace

ARG TARGETOS=linux
ARG TARGETARCH=amd64

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /workspace/bin/manager ./cmd/declarest-operator-manager

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/bin/manager /manager
USER nonroot:nonroot
ENTRYPOINT ["/manager"]
