apiVersion: v1
kind: Service
metadata:
  name: declarest-operator-webhook-service
  namespace: declarest-system
  labels:
    app.kubernetes.io/name: declarest-operator
spec:
  selector:
    app.kubernetes.io/name: declarest-operator
  ports:
    - port: 443
      targetPort: webhook-server
      protocol: TCP
      name: webhook-server
