apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: declarest-operator-validating-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: vresourcerepository-v1alpha1.declarest.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    clientConfig:
      service:
        name: declarest-operator-webhook-service
        namespace: declarest-system
        path: /validate-declarest-io-v1alpha1-resourcerepository
    rules:
      - apiGroups: ["declarest.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["resourcerepositories"]
  - name: vmanagedserver-v1alpha1.declarest.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    clientConfig:
      service:
        name: declarest-operator-webhook-service
        namespace: declarest-system
        path: /validate-declarest-io-v1alpha1-managedserver
    rules:
      - apiGroups: ["declarest.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["managedservers"]
  - name: vsecretstore-v1alpha1.declarest.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    clientConfig:
      service:
        name: declarest-operator-webhook-service
        namespace: declarest-system
        path: /validate-declarest-io-v1alpha1-secretstore
    rules:
      - apiGroups: ["declarest.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["secretstores"]
  - name: vsyncpolicy-v1alpha1.declarest.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10
    clientConfig:
      service:
        name: declarest-operator-webhook-service
        namespace: declarest-system
        path: /validate-declarest-io-v1alpha1-syncpolicy
    rules:
      - apiGroups: ["declarest.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["syncpolicies"]
