apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: declarest-operator
  namespace: declarest-system
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: declarest-operator
  namespace: declarest-system
spec:
  channel: alpha
  name: declarest-operator
  source: declarest-operator-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
