apiVersion: declarest.io/v1alpha1
kind: SecretStore
metadata:
  name: example-secret-store
spec:
  provider: file
  file:
    path: /var/lib/declarest/secrets/secrets.json
    encryption:
      passphraseRef:
        name: secret-store-file
        key: passphrase
    storage:
      existingPVC:
        name: secret-store-pvc
