apiVersion: declarest.io/v1alpha1
kind: ResourceRepository
metadata:
  name: example-repository
spec:
  type: git
  pollInterval: 1m
  resourceFormat: json
  git:
    url: https://github.com/example/declarest-resources.git
    branch: main
    auth:
      tokenSecretRef:
        name: repository-credentials
        key: token
  storage:
    existingPVC:
      name: repository-pvc
