apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - declarest_v1alpha1_resourcerepository.yaml
  - declarest_v1alpha1_managedservice.yaml
  - declarest_v1alpha1_secretstore.yaml
  - declarest_v1alpha1_syncpolicy.yaml
  - declarest_v1alpha1_repositorywebhook.yaml
  - declarest_v1alpha1_metadatabundle.yaml
  - declarest_v1alpha1_crdgenerator.yaml
