//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGenerator) DeepCopyInto(out *CRDGenerator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGenerator.
func (in *CRDGenerator) DeepCopy() *CRDGenerator {
	if in == nil {
		return nil
	}
	out := new(CRDGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CRDGenerator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorConversion) DeepCopyInto(out *CRDGeneratorConversion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorConversion.
func (in *CRDGeneratorConversion) DeepCopy() *CRDGeneratorConversion {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorConversion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorList) DeepCopyInto(out *CRDGeneratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CRDGenerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorList.
func (in *CRDGeneratorList) DeepCopy() *CRDGeneratorList {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CRDGeneratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorNames) DeepCopyInto(out *CRDGeneratorNames) {
	*out = *in
	if in.ShortNames != nil {
		in, out := &in.ShortNames, &out.ShortNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorNames.
func (in *CRDGeneratorNames) DeepCopy() *CRDGeneratorNames {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorPrinterColumn) DeepCopyInto(out *CRDGeneratorPrinterColumn) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorPrinterColumn.
func (in *CRDGeneratorPrinterColumn) DeepCopy() *CRDGeneratorPrinterColumn {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorPrinterColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorResolvedBundle) DeepCopyInto(out *CRDGeneratorResolvedBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorResolvedBundle.
func (in *CRDGeneratorResolvedBundle) DeepCopy() *CRDGeneratorResolvedBundle {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorResolvedBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorResolvedVersion) DeepCopyInto(out *CRDGeneratorResolvedVersion) {
	*out = *in
	out.MetadataBundle = in.MetadataBundle
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorResolvedVersion.
func (in *CRDGeneratorResolvedVersion) DeepCopy() *CRDGeneratorResolvedVersion {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorResolvedVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorSpec) DeepCopyInto(out *CRDGeneratorSpec) {
	*out = *in
	in.Names.DeepCopyInto(&out.Names)
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]CRDGeneratorVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conversion != nil {
		in, out := &in.Conversion, &out.Conversion
		*out = new(CRDGeneratorConversion)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorSpec.
func (in *CRDGeneratorSpec) DeepCopy() *CRDGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorStatus) DeepCopyInto(out *CRDGeneratorStatus) {
	*out = *in
	if in.ResolvedVersions != nil {
		in, out := &in.ResolvedVersions, &out.ResolvedVersions
		*out = make(map[string]CRDGeneratorResolvedVersion, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorStatus.
func (in *CRDGeneratorStatus) DeepCopy() *CRDGeneratorStatus {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDGeneratorVersion) DeepCopyInto(out *CRDGeneratorVersion) {
	*out = *in
	out.MetadataBundleRef = in.MetadataBundleRef
	if in.AdditionalPrinterColumns != nil {
		in, out := &in.AdditionalPrinterColumns, &out.AdditionalPrinterColumns
		*out = make([]CRDGeneratorPrinterColumn, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDGeneratorVersion.
func (in *CRDGeneratorVersion) DeepCopy() *CRDGeneratorVersion {
	if in == nil {
		return nil
	}
	out := new(CRDGeneratorVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeclaRESTExternalArtifact) DeepCopyInto(out *DeclaRESTExternalArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeclaRESTExternalArtifact.
func (in *DeclaRESTExternalArtifact) DeepCopy() *DeclaRESTExternalArtifact {
	if in == nil {
		return nil
	}
	out := new(DeclaRESTExternalArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeclaRESTMetadataArtifact) DeepCopyInto(out *DeclaRESTMetadataArtifact) {
	*out = *in
	if in.BundleRef != nil {
		in, out := &in.BundleRef, &out.BundleRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeclaRESTMetadataArtifact.
func (in *DeclaRESTMetadataArtifact) DeepCopy() *DeclaRESTMetadataArtifact {
	if in == nil {
		return nil
	}
	out := new(DeclaRESTMetadataArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepositorySpec) DeepCopyInto(out *GitRepositorySpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(GitRepositoryWebhookSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepositorySpec.
func (in *GitRepositorySpec) DeepCopy() *GitRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(GitRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRepositoryWebhookSpec) DeepCopyInto(out *GitRepositoryWebhookSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRepositoryWebhookSpec.
func (in *GitRepositoryWebhookSpec) DeepCopy() *GitRepositoryWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(GitRepositoryWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSSHSecretRef) DeepCopyInto(out *GitSSHSecretRef) {
	*out = *in
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KnownHostsRef != nil {
		in, out := &in.KnownHostsRef, &out.KnownHostsRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PassphraseRef != nil {
		in, out := &in.PassphraseRef, &out.PassphraseRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSSHSecretRef.
func (in *GitSSHSecretRef) DeepCopy() *GitSSHSecretRef {
	if in == nil {
		return nil
	}
	out := new(GitSSHSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProxySpec) DeepCopyInto(out *HTTPProxySpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(ProxyAuthSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProxySpec.
func (in *HTTPProxySpec) DeepCopy() *HTTPProxySpec {
	if in == nil {
		return nil
	}
	out := new(HTTPProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedService) DeepCopyInto(out *ManagedService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedService.
func (in *ManagedService) DeepCopy() *ManagedService {
	if in == nil {
		return nil
	}
	out := new(ManagedService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceAuth) DeepCopyInto(out *ManagedServiceAuth) {
	*out = *in
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(ManagedServiceOAuth2Auth)
		(*in).DeepCopyInto(*out)
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(ManagedServiceBasicAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomHeaders != nil {
		in, out := &in.CustomHeaders, &out.CustomHeaders
		*out = make([]ManagedServiceHeaderAuth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceAuth.
func (in *ManagedServiceAuth) DeepCopy() *ManagedServiceAuth {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceBasicAuth) DeepCopyInto(out *ManagedServiceBasicAuth) {
	*out = *in
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceBasicAuth.
func (in *ManagedServiceBasicAuth) DeepCopy() *ManagedServiceBasicAuth {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceHTTP) DeepCopyInto(out *ManagedServiceHTTP) {
	*out = *in
	if in.DefaultHeaders != nil {
		in, out := &in.DefaultHeaders, &out.DefaultHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Auth.DeepCopyInto(&out.Auth)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(HTTPProxySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestThrottling != nil {
		in, out := &in.RequestThrottling, &out.RequestThrottling
		*out = new(ManagedServiceRequestThrottling)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceHTTP.
func (in *ManagedServiceHTTP) DeepCopy() *ManagedServiceHTTP {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceHeaderAuth) DeepCopyInto(out *ManagedServiceHeaderAuth) {
	*out = *in
	if in.ValueRef != nil {
		in, out := &in.ValueRef, &out.ValueRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceHeaderAuth.
func (in *ManagedServiceHeaderAuth) DeepCopy() *ManagedServiceHeaderAuth {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceHeaderAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceList) DeepCopyInto(out *ManagedServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceList.
func (in *ManagedServiceList) DeepCopy() *ManagedServiceList {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceOAuth2Auth) DeepCopyInto(out *ManagedServiceOAuth2Auth) {
	*out = *in
	if in.ClientIDRef != nil {
		in, out := &in.ClientIDRef, &out.ClientIDRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceOAuth2Auth.
func (in *ManagedServiceOAuth2Auth) DeepCopy() *ManagedServiceOAuth2Auth {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceOAuth2Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceRequestThrottling) DeepCopyInto(out *ManagedServiceRequestThrottling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceRequestThrottling.
func (in *ManagedServiceRequestThrottling) DeepCopy() *ManagedServiceRequestThrottling {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceRequestThrottling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceSpec) DeepCopyInto(out *ManagedServiceSpec) {
	*out = *in
	in.HTTP.DeepCopyInto(&out.HTTP)
	out.OpenAPI = in.OpenAPI
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceSpec.
func (in *ManagedServiceSpec) DeepCopy() *ManagedServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedServiceStatus) DeepCopyInto(out *ManagedServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedServiceStatus.
func (in *ManagedServiceStatus) DeepCopy() *ManagedServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundle) DeepCopyInto(out *MetadataBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundle.
func (in *MetadataBundle) DeepCopy() *MetadataBundle {
	if in == nil {
		return nil
	}
	out := new(MetadataBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetadataBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundleCompatibility) DeepCopyInto(out *MetadataBundleCompatibility) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundleCompatibility.
func (in *MetadataBundleCompatibility) DeepCopy() *MetadataBundleCompatibility {
	if in == nil {
		return nil
	}
	out := new(MetadataBundleCompatibility)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundleConfigMapSource) DeepCopyInto(out *MetadataBundleConfigMapSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundleConfigMapSource.
func (in *MetadataBundleConfigMapSource) DeepCopy() *MetadataBundleConfigMapSource {
	if in == nil {
		return nil
	}
	out := new(MetadataBundleConfigMapSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundleList) DeepCopyInto(out *MetadataBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetadataBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundleList.
func (in *MetadataBundleList) DeepCopy() *MetadataBundleList {
	if in == nil {
		return nil
	}
	out := new(MetadataBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetadataBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundleManifest) DeepCopyInto(out *MetadataBundleManifest) {
	*out = *in
	if in.CompatibleManagedService != nil {
		in, out := &in.CompatibleManagedService, &out.CompatibleManagedService
		*out = new(MetadataBundleCompatibility)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundleManifest.
func (in *MetadataBundleManifest) DeepCopy() *MetadataBundleManifest {
	if in == nil {
		return nil
	}
	out := new(MetadataBundleManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundlePVCSource) DeepCopyInto(out *MetadataBundlePVCSource) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundlePVCSource.
func (in *MetadataBundlePVCSource) DeepCopy() *MetadataBundlePVCSource {
	if in == nil {
		return nil
	}
	out := new(MetadataBundlePVCSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundleSource) DeepCopyInto(out *MetadataBundleSource) {
	*out = *in
	if in.PullSecretRef != nil {
		in, out := &in.PullSecretRef, &out.PullSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(MetadataBundlePVCSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(MetadataBundleConfigMapSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundleSource.
func (in *MetadataBundleSource) DeepCopy() *MetadataBundleSource {
	if in == nil {
		return nil
	}
	out := new(MetadataBundleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundleSpec) DeepCopyInto(out *MetadataBundleSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundleSpec.
func (in *MetadataBundleSpec) DeepCopy() *MetadataBundleSpec {
	if in == nil {
		return nil
	}
	out := new(MetadataBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataBundleStatus) DeepCopyInto(out *MetadataBundleStatus) {
	*out = *in
	if in.Manifest != nil {
		in, out := &in.Manifest, &out.Manifest
		*out = new(MetadataBundleManifest)
		(*in).DeepCopyInto(*out)
	}
	if in.LastResolvedTime != nil {
		in, out := &in.LastResolvedTime, &out.LastResolvedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataBundleStatus.
func (in *MetadataBundleStatus) DeepCopy() *MetadataBundleStatus {
	if in == nil {
		return nil
	}
	out := new(MetadataBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCTemplateSpec) DeepCopyInto(out *PVCTemplateSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCTemplateSpec.
func (in *PVCTemplateSpec) DeepCopy() *PVCTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PVCTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyAuthSpec) DeepCopyInto(out *ProxyAuthSpec) {
	*out = *in
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyAuthSpec.
func (in *ProxyAuthSpec) DeepCopy() *ProxyAuthSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWebhook) DeepCopyInto(out *RepositoryWebhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWebhook.
func (in *RepositoryWebhook) DeepCopy() *RepositoryWebhook {
	if in == nil {
		return nil
	}
	out := new(RepositoryWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryWebhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWebhookBranchFilter) DeepCopyInto(out *RepositoryWebhookBranchFilter) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWebhookBranchFilter.
func (in *RepositoryWebhookBranchFilter) DeepCopy() *RepositoryWebhookBranchFilter {
	if in == nil {
		return nil
	}
	out := new(RepositoryWebhookBranchFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWebhookList) DeepCopyInto(out *RepositoryWebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryWebhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWebhookList.
func (in *RepositoryWebhookList) DeepCopy() *RepositoryWebhookList {
	if in == nil {
		return nil
	}
	out := new(RepositoryWebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryWebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWebhookSpec) DeepCopyInto(out *RepositoryWebhookSpec) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
	out.SecretRef = in.SecretRef
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]RepositoryWebhookEvent, len(*in))
		copy(*out, *in)
	}
	if in.BranchFilter != nil {
		in, out := &in.BranchFilter, &out.BranchFilter
		*out = new(RepositoryWebhookBranchFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWebhookSpec.
func (in *RepositoryWebhookSpec) DeepCopy() *RepositoryWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryWebhookStatus) DeepCopyInto(out *RepositoryWebhookStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEventTime != nil {
		in, out := &in.LastEventTime, &out.LastEventTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryWebhookStatus.
func (in *RepositoryWebhookStatus) DeepCopy() *RepositoryWebhookStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryWebhookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRepository) DeepCopyInto(out *ResourceRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRepository.
func (in *ResourceRepository) DeepCopy() *ResourceRepository {
	if in == nil {
		return nil
	}
	out := new(ResourceRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRepositoryAuth) DeepCopyInto(out *ResourceRepositoryAuth) {
	*out = *in
	if in.TokenRef != nil {
		in, out := &in.TokenRef, &out.TokenRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SSHSecretRef != nil {
		in, out := &in.SSHSecretRef, &out.SSHSecretRef
		*out = new(GitSSHSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRepositoryAuth.
func (in *ResourceRepositoryAuth) DeepCopy() *ResourceRepositoryAuth {
	if in == nil {
		return nil
	}
	out := new(ResourceRepositoryAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRepositoryList) DeepCopyInto(out *ResourceRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRepositoryList.
func (in *ResourceRepositoryList) DeepCopy() *ResourceRepositoryList {
	if in == nil {
		return nil
	}
	out := new(ResourceRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRepositorySpec) DeepCopyInto(out *ResourceRepositorySpec) {
	*out = *in
	out.PollInterval = in.PollInterval
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitRepositorySpec)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRepositorySpec.
func (in *ResourceRepositorySpec) DeepCopy() *ResourceRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(ResourceRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRepositoryStatus) DeepCopyInto(out *ResourceRepositoryStatus) {
	*out = *in
	if in.LastFetchedTime != nil {
		in, out := &in.LastFetchedTime, &out.LastFetchedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRepositoryStatus.
func (in *ResourceRepositoryStatus) DeepCopy() *ResourceRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStore) DeepCopyInto(out *SecretStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStore.
func (in *SecretStore) DeepCopy() *SecretStore {
	if in == nil {
		return nil
	}
	out := new(SecretStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreFileEncryption) DeepCopyInto(out *SecretStoreFileEncryption) {
	*out = *in
	if in.KeyRef != nil {
		in, out := &in.KeyRef, &out.KeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PassphraseRef != nil {
		in, out := &in.PassphraseRef, &out.PassphraseRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreFileEncryption.
func (in *SecretStoreFileEncryption) DeepCopy() *SecretStoreFileEncryption {
	if in == nil {
		return nil
	}
	out := new(SecretStoreFileEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreFileSpec) DeepCopyInto(out *SecretStoreFileSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Encryption.DeepCopyInto(&out.Encryption)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreFileSpec.
func (in *SecretStoreFileSpec) DeepCopy() *SecretStoreFileSpec {
	if in == nil {
		return nil
	}
	out := new(SecretStoreFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreList) DeepCopyInto(out *SecretStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreList.
func (in *SecretStoreList) DeepCopy() *SecretStoreList {
	if in == nil {
		return nil
	}
	out := new(SecretStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreSpec) DeepCopyInto(out *SecretStoreSpec) {
	*out = *in
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(SecretStoreVaultSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(SecretStoreFileSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreSpec.
func (in *SecretStoreSpec) DeepCopy() *SecretStoreSpec {
	if in == nil {
		return nil
	}
	out := new(SecretStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreStatus) DeepCopyInto(out *SecretStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreStatus.
func (in *SecretStoreStatus) DeepCopy() *SecretStoreStatus {
	if in == nil {
		return nil
	}
	out := new(SecretStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreVaultAppRoleAuth) DeepCopyInto(out *SecretStoreVaultAppRoleAuth) {
	*out = *in
	if in.RoleIDRef != nil {
		in, out := &in.RoleIDRef, &out.RoleIDRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretIDRef != nil {
		in, out := &in.SecretIDRef, &out.SecretIDRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreVaultAppRoleAuth.
func (in *SecretStoreVaultAppRoleAuth) DeepCopy() *SecretStoreVaultAppRoleAuth {
	if in == nil {
		return nil
	}
	out := new(SecretStoreVaultAppRoleAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreVaultAuth) DeepCopyInto(out *SecretStoreVaultAuth) {
	*out = *in
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(SecretStoreVaultTokenAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.Userpass != nil {
		in, out := &in.Userpass, &out.Userpass
		*out = new(SecretStoreVaultUserpassAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.AppRole != nil {
		in, out := &in.AppRole, &out.AppRole
		*out = new(SecretStoreVaultAppRoleAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreVaultAuth.
func (in *SecretStoreVaultAuth) DeepCopy() *SecretStoreVaultAuth {
	if in == nil {
		return nil
	}
	out := new(SecretStoreVaultAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreVaultSpec) DeepCopyInto(out *SecretStoreVaultSpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(HTTPProxySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreVaultSpec.
func (in *SecretStoreVaultSpec) DeepCopy() *SecretStoreVaultSpec {
	if in == nil {
		return nil
	}
	out := new(SecretStoreVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreVaultTokenAuth) DeepCopyInto(out *SecretStoreVaultTokenAuth) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreVaultTokenAuth.
func (in *SecretStoreVaultTokenAuth) DeepCopy() *SecretStoreVaultTokenAuth {
	if in == nil {
		return nil
	}
	out := new(SecretStoreVaultTokenAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreVaultUserpassAuth) DeepCopyInto(out *SecretStoreVaultUserpassAuth) {
	*out = *in
	if in.UsernameRef != nil {
		in, out := &in.UsernameRef, &out.UsernameRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordRef != nil {
		in, out := &in.PasswordRef, &out.PasswordRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreVaultUserpassAuth.
func (in *SecretStoreVaultUserpassAuth) DeepCopy() *SecretStoreVaultUserpassAuth {
	if in == nil {
		return nil
	}
	out := new(SecretStoreVaultUserpassAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.ExistingPVC != nil {
		in, out := &in.ExistingPVC, &out.ExistingPVC
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicy) DeepCopyInto(out *SyncPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicy.
func (in *SyncPolicy) DeepCopy() *SyncPolicy {
	if in == nil {
		return nil
	}
	out := new(SyncPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SyncPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicyList) DeepCopyInto(out *SyncPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SyncPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicyList.
func (in *SyncPolicyList) DeepCopy() *SyncPolicyList {
	if in == nil {
		return nil
	}
	out := new(SyncPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SyncPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicyResourceStats) DeepCopyInto(out *SyncPolicyResourceStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicyResourceStats.
func (in *SyncPolicyResourceStats) DeepCopy() *SyncPolicyResourceStats {
	if in == nil {
		return nil
	}
	out := new(SyncPolicyResourceStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicySource) DeepCopyInto(out *SyncPolicySource) {
	*out = *in
	if in.Recursive != nil {
		in, out := &in.Recursive, &out.Recursive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicySource.
func (in *SyncPolicySource) DeepCopy() *SyncPolicySource {
	if in == nil {
		return nil
	}
	out := new(SyncPolicySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicySpec) DeepCopyInto(out *SyncPolicySpec) {
	*out = *in
	out.ResourceRepositoryRef = in.ResourceRepositoryRef
	out.ManagedServiceRef = in.ManagedServiceRef
	out.SecretStoreRef = in.SecretStoreRef
	in.Source.DeepCopyInto(&out.Source)
	out.Sync = in.Sync
	if in.SyncInterval != nil {
		in, out := &in.SyncInterval, &out.SyncInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicySpec.
func (in *SyncPolicySpec) DeepCopy() *SyncPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SyncPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicyStatus) DeepCopyInto(out *SyncPolicyStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulSyncTime != nil {
		in, out := &in.LastSuccessfulSyncTime, &out.LastSuccessfulSyncTime
		*out = (*in).DeepCopy()
	}
	if in.LastFullResyncTime != nil {
		in, out := &in.LastFullResyncTime, &out.LastFullResyncTime
		*out = (*in).DeepCopy()
	}
	out.ResourceStats = in.ResourceStats
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicyStatus.
func (in *SyncPolicyStatus) DeepCopy() *SyncPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SyncPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncPolicySyncOptions) DeepCopyInto(out *SyncPolicySyncOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncPolicySyncOptions.
func (in *SyncPolicySyncOptions) DeepCopy() *SyncPolicySyncOptions {
	if in == nil {
		return nil
	}
	out := new(SyncPolicySyncOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.CACertRef != nil {
		in, out := &in.CACertRef, &out.CACertRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientCertRef != nil {
		in, out := &in.ClientCertRef, &out.ClientCertRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKeyRef != nil {
		in, out := &in.ClientKeyRef, &out.ClientKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}
