apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarest-operator
spec:
  template:
    spec:
      volumes:
        - name: state
          emptyDir: {}
        - name: tmp
          emptyDir: {}
